spring.application.name=demo
# URL de conexão com o banco
spring.datasource.url=jdbc:mysql://localhost:3306/professor?useSSL=false&serverTimezone=UTC

# Usuário e senha do MySQL
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# Driver JDBC do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create


