
management.endpoints.web.exposure.include=*
management.endpoints.env.enabled=true
management.endpoints.web.exposure.exclude= info,health

#
# change spring boot embedded server port
#
server.port=7070

#
#Set the context path of the application
#
server.servlet.context-path=/mycoolapp