    -- Table: public.category

-- DROP TABLE IF EXISTS public.category;

CREATE TABLE IF NOT EXISTS public.category
(
    category_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(60) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    parent_category_id integer,
    CONSTRAINT category_pkey PRIMARY KEY (category_id),
    CONSTRAINT category_parent_category_id_fkey FOREIGN KEY (parent_category_id)
        REFERENCES public.category (category_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.category
    OWNER to postgres;

-- Table: public.customer

-- DROP TABLE IF EXISTS public.customer;

CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id integer NOT NULL DEFAULT nextval('customer_customer_id_seq'::regclass),
    contact_name character varying(30) COLLATE pg_catalog."default",
    company_name character varying(40) COLLATE pg_catalog."default",
    contact_email character varying(128) COLLATE pg_catalog."default",
    address character varying(120) COLLATE pg_catalog."default",
    city character varying(30) COLLATE pg_catalog."default",
    country character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customer
    OWNER to postgres;

-- Table: public.employee

-- DROP TABLE IF EXISTS public.employee;

CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id integer NOT NULL DEFAULT nextval('employee_employee_id_seq'::regclass),
    last_name character varying(40) COLLATE pg_catalog."default",
    first_name character varying(20) COLLATE pg_catalog."default",
    birth_date date,
    hire_date date,
    address character varying(128) COLLATE pg_catalog."default",
    city character varying(30) COLLATE pg_catalog."default",
    country character varying(30) COLLATE pg_catalog."default",
    reports_to integer,
    CONSTRAINT employee_pkey PRIMARY KEY (employee_id),
    CONSTRAINT employee_reports_to_fkey FOREIGN KEY (reports_to)
        REFERENCES public.employee (employee_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.employee
    OWNER to postgres;

-- Table: public.product

-- DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL DEFAULT nextval('product_product_id_seq'::regclass),
    product_name character varying(40) COLLATE pg_catalog."default",
    category_id integer,
    quantity_per_unit integer,
    unit_price numeric(10,2),
    units_in_stock integer,
    discontinued boolean,
    CONSTRAINT product_pkey PRIMARY KEY (product_id),
    CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id)
        REFERENCES public.category (category_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.product
    OWNER to postgres;

-- Table: public.purchase

-- DROP TABLE IF EXISTS public.purchase;

CREATE TABLE IF NOT EXISTS public.purchase
(
    purchase_id integer NOT NULL DEFAULT nextval('purchase_purchase_id_seq'::regclass),
    customer_id integer,
    employee_id integer,
    total_price numeric(10,2),
    purchase_date timestamp without time zone,
    shipped_date timestamp without time zone,
    ship_address character varying(60) COLLATE pg_catalog."default",
    ship_city character varying(15) COLLATE pg_catalog."default",
    ship_country character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT purchase_pkey PRIMARY KEY (purchase_id),
    CONSTRAINT purchase_employee_id_fkey FOREIGN KEY (employee_id)
        REFERENCES public.employee (employee_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.purchase
    OWNER to postgres;