version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql_agenda
    environment:
      MYSQL_DATABASE: agenda_db
      MYSQL_ROOT_PASSWORD: ASTimperial@12
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    image: agenda:latest
    container_name: agenda_cli
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/agenda_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=ASTimperial@12
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true                 # mude para true para ver se conecta e cria tabelas
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true

volumes:
  mysql_data: